name: Testomat.io CI

on:
  workflow_dispatch: # allow manual triggering from Testomat
    inputs:
      grep:
        description: "Filter tests to run (optional)"
        required: false
        default: ""
      run:
        description: "Testomat Run ID"
        required: false
      testomatio:
        description: "Testomat API token"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.grep }}" != "" ]; then
            npx playwright test --grep "${{ github.event.inputs.grep }}" --reporter=list,json --output=report || true
          else
            npx playwright test --reporter=list,json --output=report || true
          fi

      - name: Upload results to Testomat.io
        run: |
          npx @testomatio/reporter xml tests/test-results/junit.xml
            --token "${{ github.event.inputs.testomatio }}" 
            --run "${{ github.event.inputs.run }}"